def operation():
    a=input()
    b=input()
    c=input()
    print(a>b and a>c)
    print(a>b or a>c)
    print(a>b and b>c)
    print(a>b or b>c)
    print(a<b and a<c) 
    print(a<b or a<c)
    print(a<b and b<c)
    print(a<b or b<c)
    print(a==b and a<c)
    print(a==b or a<c)
    print(a==b and b>c)
    print(a==b or b>c)
    print(a==b and b==c)
    print(a==b or b==c)
    print(a!=b and b==c)
    print(a!=b or b!=c)
operation()

